#!/bin/sh


sudo dpkg --configure -a
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y python-numpy python-dev cmake zlib1g-dev libjpeg-dev xvfb libav-tools xorg-dev python-opengl libboost-all-dev libsdl2-dev swig
pip install gym[all]
